[package]
name = "crsql_integration_check"
version = "0.0.1"
edition = "2021"
authors = ["Matt Wonlaw"]
description = "rs integration check for crsqlite"
keywords = ["sqlite"]
license = "Apache-2.0"

[lib]
name = "crsql_integration_check"
crate-type = ["staticlib"]

[dependencies]
sqlite_nostd = { path="../sqlite-rs-embedded/sqlite_nostd", features=["static", "omit_load_extension"] }
crsql_bundle = { path="../bundle", features=["static", "omit_load_extension", "test"] }
cargo-valgrind = "2.1.0"
libc-print = "0.1.21"

[build-dependencies]
cc = "1.0"

[features]
static = []
omit_load_extension = []
